name: Deployment

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    test:
        name: Run Jest

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Restore NPM dependencies from cache
              uses: actions/cache@v4
              id: restore-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              if: steps.restore-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Run the tests
              run: npm test

    deploy:
        name: Deploy to github pages
        needs: test

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Restore NPM dependencies from cache
              uses: actions/cache@v4
              id: restore-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              if: steps.restore-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Build
              run: npm run build:prod

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: "dist"

            - name: Configure Pages
              uses: actions/configure-pages@v4

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v3
