name: Main Deployment

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Run Jest tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Run Jest tests
              run: yarn test

    deploy:
        name: Deploy to GHP
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Jest tests
              run: yarn deploy
