name: Main Deployment

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

    test:
        name: Run Jest tests
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: npm run test

    deploy:
        name: Deploy to github pages
        needs: test
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
