name: Test

on:
    push:
        branches:
            - dev

    pull_request:
        branches:
            - dev

jobs:
    test:
        name: Run Jest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Restore NPM dependencies from cache
              uses: actions/cache@v4
              id: restore-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              if: steps.restore-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Run the tests
              run: npm test
