name: Test

on:
    push:
        branches:
            - dev

    pull_request:
        branches:
            - dev

jobs:
    test:
        name: Run Jest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Run the tests
              run: npm test
